/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ModelImport } from './routes/model'
import { Route as MatcherImport } from './routes/matcher'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ModelRoute = ModelImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRoute,
} as any)

const MatcherRoute = MatcherImport.update({
  id: '/matcher',
  path: '/matcher',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/matcher': {
      id: '/matcher'
      path: '/matcher'
      fullPath: '/matcher'
      preLoaderRoute: typeof MatcherImport
      parentRoute: typeof rootRoute
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matcher': typeof MatcherRoute
  '/model': typeof ModelRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matcher': typeof MatcherRoute
  '/model': typeof ModelRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/matcher': typeof MatcherRoute
  '/model': typeof ModelRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matcher' | '/model'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matcher' | '/model'
  id: '__root__' | '/' | '/matcher' | '/model'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatcherRoute: typeof MatcherRoute
  ModelRoute: typeof ModelRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatcherRoute: MatcherRoute,
  ModelRoute: ModelRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/matcher",
        "/model"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/matcher": {
      "filePath": "matcher.tsx"
    },
    "/model": {
      "filePath": "model.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
